name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Build Release
      run: dotnet build src/VirtualDesktopIndicator.csproj --configuration Release --no-restore --verbosity minimal /p:TreatWarningsAsErrors=false /p:EnforceCodeStyleInBuild=false

    - name: Publish Portable (win-x64)
      run: |
        dotnet publish src/VirtualDesktopIndicator.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output ./publish/portable `
          -p:PublishSingleFile=true

    - name: Publish Framework-Dependent
      run: |
        dotnet publish src/VirtualDesktopIndicator.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained false `
          --output ./publish/framework-dependent

    - name: Create Release Archives
      run: |
        # Create portable archive
        Compress-Archive -Path "./publish/portable/*" -DestinationPath "./VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-portable.zip"
        
        # Create framework-dependent archive  
        Compress-Archive -Path "./publish/framework-dependent/*" -DestinationPath "./VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-framework-dependent.zip"

    - name: Generate SHA256 Checksums
      run: |
        Get-FileHash -Algorithm SHA256 "VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-portable.zip" | Out-File -Append checksums.txt
        Get-FileHash -Algorithm SHA256 "VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-framework-dependent.zip" | Out-File -Append checksums.txt

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-portable.zip
          VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-framework-dependent.zip
          checksums.txt
        body: |
          ## VirtualDesktopIndicator ${{ github.ref_name }}
          
          A modern, free alternative to paid virtual desktop tools for Windows.
          
          ### 📥 Download Options
          
          - **Portable (Recommended)**: `VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-portable.zip`
            - No installation required, no .NET runtime needed
            - Extract and run `VirtualDesktopIndicator.exe`
          
          - **Framework-Dependent**: `VirtualDesktopIndicator-${{ github.ref_name }}-win-x64-framework-dependent.zip`
            - Requires .NET 8 Runtime
            - Smaller download size
          
          ### 🔐 Security
          SHA256 checksums are provided in `checksums.txt` for download verification.
          
          ### 🎯 System Requirements
          - Windows 10 version 1903+ or Windows 11
          - x64 architecture
          - No admin privileges required
          
          **Full Changelog**: https://github.com/balgaly/VirtualDesktopIndicator/compare/v1.0.0...${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}